packages:
  - 'packages/*'

catalog:
  postcss-mixins: 11.0.3
  postcss-simple-vars: 7.0.1
  postcss-nested: 7.0.2
  postcss: 8.5.3
  vue: 3.5.13
  vite: 6.3.4
  typescript: 5.8.3
  '@types/node': 22.15.3
  '@vitejs/plugin-vue': 5.2.3
  terser: 5.39.0
  '@floating-ui/vue': 1.1.6
  '@laynezh/vite-plugin-lib-assets': 1.1.0
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.3
