packages:
  - 'packages/*'

catalog:
  postcss-mixins: 11.0.3
  postcss-simple-vars: 7.0.1
  postcss-nested: 7.0.2
  postcss: 8.5.1
  vue: 3.5.13
  vite: 6.1.0
  typescript: 5.7.3
  '@types/node': 20.15.0
  '@vitejs/plugin-vue': 5.2.1
  terser: 5.37.0
  '@floating-ui/vue': 1.1.6
  '@laynezh/vite-plugin-lib-assets': 1.0.0
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.0
