packages:
  - 'packages/*'

catalog:
  postcss-mixins: 11.0.3
  postcss-simple-vars: 7.0.1
  postcss-nested: 6.2.0
  postcss: 8.4.47
  vue: 3.5.12
  vite: 5.4.10
  typescript: 5.6.3
  '@types/node': 20.15.0
  '@vitejs/plugin-vue': 5.1.4
  '@rollup/plugin-terser': 0.4.4
  '@floating-ui/vue': 1.1.5
  '@laynezh/vite-plugin-lib-assets': 0.5.24
  vite-plugin-css-injected-by-js: 3.5.1
  vite-plugin-dts: 4.3.0
